codefog_instagram:
    access_token_ttl: 3600 # access token local time to live after which Contao will make a request to refresh the token, in seconds
    cache_ttl: 3600 # feed data cache local time to live, in seconds