# Alle Routen wurden in das vsm-helper-tools Bundle verschoben
# Die folgenden Routen werden nur zur Dokumentation beibehalten

# video_render:
#     path: /video/render
#     controller: App\Controller\VideoRenderController::renderVideo
#     methods: [ POST ]
#     defaults:
#       _scope: frontend
# stripe_webhook:
#   path: /stripe/webhook
#   controller: App\Controller\StripeWebhookController::webhook
#   methods: [ POST ]
#   defaults:
#     _scope: frontend

# stripe_create_payment_intent:
#   path: /stripe/create-payment-intent
#   controller: App\Controller\StripeWebhookController::createPaymentIntent
#   methods: [ POST ]
#   defaults:
#     _scope: frontend

# stripe_get_price:
#   path: /stripe/get-price
#   controller: App\Controller\StripeWebhookController::getPrice
#   methods: [ POST ]
#   defaults:
#     _scope: frontend

# stripe_check_user:
#   path: /stripe/check-user
#   controller: App\Controller\StripeWebhookController::checkUser
#   methods: [ POST ]
#   defaults:
#     _scope: frontend