services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Template Optimization Listener (Canonical URLs, Asset Loading, Link Enhancement)
    App\EventListener\TemplateOptimizationListener:
        tags:
            - { name: 'contao.hook', hook: 'parseTemplate', priority: 100 }

    # Caeli Area Check AJAX Controllers
    CaeliWind\CaeliAreaCheckBundle\Controller\FrontendModule\AreaCheckMapController:
        tags: ['controller.service_arguments']
        public: true 