services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\PlunkService:
        arguments:
            $publicKey: '%env(PLUNK_PUBLIC_KEY)%'
            $secretKey: '%env(PLUNK_SECRET_KEY)%'
            $client: '@http_client'
            $logger: '@logger'

    App\Controller\StripeWebhookController:
        arguments:
            $container: '@service_container'
            $webhookSecret: '%env(STRIPE_WEBHOOK_SECRET)%'
            $stripeSecretKey: '%env(STRIPE_SECRET_KEY)%'
            $framework: '@contao.framework'
            $plunkService: '@App\Service\PlunkService'
            $logger: '@monolog.logger.contao'
        tags: ['controller.service_arguments']